"""empty message

Revision ID: 08111b9bdb66
Revises: bd6c48a56697
Create Date: 2024-10-15 15:26:57.238933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08111b9bdb66'
down_revision = 'bd6c48a56697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deputy', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_deputy')

    # ### end Alembic commands ###
