"""empty message

Revision ID: 0e37a088b595
Revises: 1c2bcb9f7562
Create Date: 2024-10-14 12:06:03.571470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e37a088b595'
down_revision = '1c2bcb9f7562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
