"""add is_бессрочно field to Task

Revision ID: 1c2bcb9f7562
Revises: 66acff31331a
Create Date: 2024-10-14 11:45:14.158184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2bcb9f7562'
down_revision = '66acff31331a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_бессрочно', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('for_review', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('for_review')
        batch_op.drop_column('is_бессрочно')

    # ### end Alembic commands ###
