"""empty message

Revision ID: 7dde5b51e3a1
Revises: 5a9e75da0344
Create Date: 2024-10-09 11:04:14.519869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dde5b51e3a1'
down_revision = '5a9e75da0344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'executor', ['executor_id'], ['id'])
        batch_op.drop_column('executor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executor', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('executor_id')

    op.drop_table('executor')
    # ### end Alembic commands ###
